# -*- python -*-
import os

from lsst.sconsUtils import env, scripts

scripts.BasicSConscript.tests(pyList=[])

# HOME makes astropy happier
# OSPL_HOME is wanted but not required by OpenSplice
# OSPL_URI is required by OpenSplice
# ADLINK_LICENSE is needed by licensed OpenSplice
for name in ("HOME", "OSPL_HOME", "OSPL_URI", "ADLINK_LICENSE"):
    val = os.environ.get(name)
    if val is not None:
        env.AppendENVPath(name, val)
