{% set data = load_setup_py_data() %}

package:
  name: ts-salobj
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_OCS_DIR

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-utils
  source_files:
      # .git is needed to test reading older git hashes of config files
    - .git
    - bin
    - pyproject.toml
    - python
    - schema
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - pytest-asyncio
    - pytest-flake8
    - pytest-runner
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - aiohttp
    - aiokafka
    - kafkit
    - astropy >=5
    - boto3
    - moto
    - ts-utils
