{% set data = load_setup_py_data() %}

package:
  name: ts-salobj
  version: {{ data.get('version') }}

source:
  path: ../
#  git_url: https://github.com/lsst-ts/ts_salobj
#  git_rev: {{ TS_SALOBJ_VERSION }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_OCS_DIR

test:
  requires:
    - pytest
    - asynctest
    - pytest-asyncio
    - pytest-flake8
    - pytest-tornasync
    - pytest-cov
    - asynctest
    - numpy
    - astropy
    - jsonschema
    - pyyaml
    - boto3
    - moto
    - ts-dds
    - ts-idl
  source_files:
    - python
    - bin
    - tests
    - schema
    - setup.cfg
    - .git
    - .githooks
  commands:
    - pytest --ignore tests/test_salpy_to_either.py --ignore tests/test_salobj_to_either.py

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
    - asynctest
    - pytest-asyncio
    - pytest-flake8
  run:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - astropy
    - jsonschema
    - pyyaml
    - boto3
    - moto
    - ts-dds
