{% set data = load_setup_py_data() %}

package:
  name: ts-salobj
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-utils
    - ts-xml
  source_files:
      # .git is needed to test reading older git hashes of config files
    - .git
    - bin
    - pyproject.toml
    - python
    - schema
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - pytest-asyncio
    - pytest-flake8
    - pytest-runner
    - python {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - astropy >=5
    - boto3
    - jsonschema
    - moto >=3
    - numpy ~=1.20
    - python {{ python }}
    - python-confluent-kafka
    - pyyaml
    - setuptools
    - setuptools_scm
    - ts-idl {{ idl_version }}
    - ts-utils
    - ts-xml
