{% set data = load_setup_py_data() %}

package:
  name: ts-salobj
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4
    - ts-utils
    - ts-xml  {{ xml_version }}
  source_files:
      # .git is needed to test reading older git hashes of config files
    - .git
    - bin
    - pyproject.toml
    - python
    - schema
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - astropy >=5.2
    - boto3
    - fastavro
    - jsonschema
    - moto >=5
    - numpy
    - python {{ python }}
    - python-confluent-kafka >=2.0.2
    - httpx
    - cachetools
    - pyyaml
    - setuptools
    - setuptools_scm
    - ts-utils
    - ts-xml >=20
